# Generated by Django 4.1.2 on 2022-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_courses_description_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
